/**
 * 扩展背景主题（照片 + 渐变/纹理）
 * 照片文件在 public/covers/biz-*.jpg；由 scripts/fetch_theme_covers.py 拉取。
 * 勿手改清单与文件名映射时不同步。
 */

import type { ThemeBackground, ThemePack } from "./site-theme";

const PHOTO_VEIL_LIGHT =
  "linear-gradient(180deg, rgba(255,255,255,0.88) 0%, rgba(255,255,255,0.78) 42%, rgba(248,250,252,0.9) 100%)";
const PHOTO_VEIL_WARM =
  "linear-gradient(180deg, rgba(255,252,247,0.9) 0%, rgba(255,248,240,0.8) 45%, rgba(247,243,236,0.92) 100%)";
const PHOTO_VEIL_COOL =
  "linear-gradient(180deg, rgba(245,249,252,0.9) 0%, rgba(241,245,249,0.82) 48%, rgba(238,242,246,0.93) 100%)";
const PHOTO_VEIL_CYBER =
  "linear-gradient(180deg, rgba(6,8,20,0.68) 0%, rgba(8,10,24,0.55) 36%, rgba(4,6,16,0.74) 100%), radial-gradient(ellipse 70% 48% at 8% -10%, rgba(34,211,238,0.38), transparent 56%), radial-gradient(ellipse 55% 40% at 92% 2%, rgba(232,121,249,0.32), transparent 54%), radial-gradient(ellipse 48% 34% at 72% 18%, rgba(168,85,247,0.22), transparent 52%), radial-gradient(ellipse 50% 32% at 48% 100%, rgba(251,146,60,0.2), transparent 55%), radial-gradient(ellipse 40% 28% at 22% 78%, rgba(163,230,53,0.14), transparent 50%)";

function photoLayers(imageUrl: string, veil: string) {
  return `${veil}, url("${imageUrl}") center / cover no-repeat`;
}

export const EXTRA_THEME_BACKGROUNDS: ThemeBackground[] = [
  {
    id: "grad-pearl-sky",
    name: "珍珠白空",
    kind: "gradient",
    preview: "radial-gradient(ellipse 80% 50% at 12% -8%, rgba(56,189,248,0.28), transparent 55%), linear-gradient(180deg,#ffffff,#eef6ff 55%,#e8f0f8)",
    layers: "radial-gradient(ellipse 80% 50% at 12% -8%, rgba(56,189,248,0.16), transparent 55%), radial-gradient(ellipse 50% 35% at 90% 10%, rgba(14,165,233,0.08), transparent 50%), linear-gradient(180deg,#ffffff 0%, var(--bg) 48%, #e8f0f8 100%)",
  },
  {
    id: "grad-graphite",
    name: "石墨商务",
    kind: "gradient",
    preview: "linear-gradient(145deg,#f8fafc,#cbd5e1 40%,#475569)",
    layers: "radial-gradient(ellipse 60% 40% at 20% 0%, rgba(71,85,105,0.12), transparent 55%), linear-gradient(180deg,#ffffff 0%, var(--bg) 50%, #e2e8f0 100%)",
  },
  {
    id: "grad-ocean-ink",
    name: "海蓝墨色",
    kind: "gradient",
    preview: "radial-gradient(ellipse at 20% 0%, rgba(3,105,161,0.35), transparent 50%), linear-gradient(180deg,#f0f9ff,#e0f2fe)",
    layers: "radial-gradient(ellipse 70% 45% at 15% -8%, rgba(3,105,161,0.18), transparent 55%), linear-gradient(180deg,#ffffff 0%, var(--bg) 50%, #dbeafe 100%)",
  },
  {
    id: "grad-champagne",
    name: "香槟金辉",
    kind: "gradient",
    preview: "radial-gradient(ellipse at 80% 0%, rgba(217,119,6,0.22), transparent 50%), linear-gradient(180deg,#fffbeb,#fef3c7)",
    layers: "radial-gradient(ellipse 65% 40% at 85% 0%, rgba(217,119,6,0.12), transparent 55%), linear-gradient(180deg,#fffdf7 0%, var(--bg) 48%, #fef3c7 100%)",
  },
  {
    id: "grad-mint-corp",
    name: "薄荷机构",
    kind: "gradient",
    preview: "radial-gradient(ellipse at 15% 0%, rgba(13,148,136,0.28), transparent 50%), linear-gradient(180deg,#f0fdfa,#ccfbf1)",
    layers: "radial-gradient(ellipse 70% 45% at 12% -8%, rgba(13,148,136,0.14), transparent 55%), linear-gradient(180deg,#ffffff 0%, var(--bg) 50%, #ccfbf1 100%)",
  },
  {
    id: "grad-midnight-navy",
    name: "午夜海军蓝",
    kind: "gradient",
    preview: "radial-gradient(ellipse at 20% 0%, rgba(30,64,175,0.45), transparent 50%), linear-gradient(180deg,#0f172a,#020617)",
    layers: "radial-gradient(ellipse 75% 48% at 12% -10%, rgba(59,130,246,0.22), transparent 55%), linear-gradient(180deg,#1e293b 0%, var(--bg) 48%, #020617 100%)",
  },
  {
    id: "grad-silver-mesh",
    name: "银灰织网",
    kind: "pattern",
    preview: "linear-gradient(90deg,rgba(100,116,139,0.1) 1px,transparent 1px),linear-gradient(rgba(100,116,139,0.1) 1px,transparent 1px),#f1f5f9",
    layers: "linear-gradient(180deg,rgba(255,255,255,0.8),rgba(241,245,249,0.92)),linear-gradient(90deg,rgba(100,116,139,0.05) 1px,transparent 1px) 0 0/32px 32px,linear-gradient(rgba(100,116,139,0.05) 1px,transparent 1px) 0 0/32px 32px,linear-gradient(180deg,#ffffff 0%,var(--bg) 100%)",
  },
  {
    id: "grad-aurora-soft",
    name: "柔光极光",
    kind: "gradient",
    preview: "radial-gradient(ellipse at 10% 0%, rgba(34,211,238,0.3), transparent 45%), radial-gradient(ellipse at 90% 20%, rgba(125,211,252,0.25), transparent 45%), linear-gradient(180deg,#f8fafc,#e0f2fe)",
    layers: "radial-gradient(ellipse 70% 45% at 8% -8%, rgba(34,211,238,0.14), transparent 55%), radial-gradient(ellipse 55% 38% at 92% 8%, rgba(125,211,252,0.12), transparent 52%), linear-gradient(180deg,#ffffff 0%, var(--bg) 48%, #e0f2fe 100%)",
  },
  {
    id: "grad-sandstone",
    name: "砂岩暖昼",
    kind: "gradient",
    preview: "radial-gradient(ellipse at 70% 0%, rgba(180,83,9,0.18), transparent 50%), linear-gradient(180deg,#fff7ed,#ffedd5)",
    layers: "radial-gradient(ellipse 65% 40% at 80% 0%, rgba(180,83,9,0.1), transparent 55%), linear-gradient(180deg,#fffaf5 0%, var(--bg) 48%, #ffedd5 100%)",
  },
  {
    id: "grad-ice-crystal",
    name: "冰晶冷调",
    kind: "gradient",
    preview: "radial-gradient(ellipse at 50% 0%, rgba(186,230,253,0.7), transparent 55%), linear-gradient(180deg,#f0f9ff,#bae6fd)",
    layers: "radial-gradient(ellipse 80% 50% at 50% -10%, rgba(125,211,252,0.2), transparent 55%), linear-gradient(180deg,#ffffff 0%, var(--bg) 50%, #e0f2fe 100%)",
  },
  {
    id: "grad-executive-ink",
    name: "高管墨蓝",
    kind: "gradient",
    preview: "linear-gradient(160deg,#1e3a5f,#0c1929 60%,#082f49)",
    layers: "radial-gradient(ellipse 60% 40% at 15% 0%, rgba(56,189,248,0.15), transparent 55%), linear-gradient(180deg,#1e293b 0%, var(--bg) 50%, #0c1929 100%)",
  },
  {
    id: "grad-cloud-layer",
    name: "层云柔白",
    kind: "gradient",
    preview: "radial-gradient(ellipse at 30% 20%, rgba(255,255,255,0.9), transparent 50%), linear-gradient(180deg,#f8fafc,#e2e8f0)",
    layers: "radial-gradient(ellipse 70% 50% at 25% 10%, rgba(255,255,255,0.7), transparent 55%), linear-gradient(180deg,#ffffff 0%, var(--bg) 55%, #e2e8f0 100%)",
  },
  {
    id: "grad-copper-line",
    name: "铜线勾勒",
    kind: "gradient",
    preview: "radial-gradient(ellipse at 90% 0%, rgba(234,88,12,0.25), transparent 45%), linear-gradient(180deg,#fff7ed,#ffedd5)",
    layers: "radial-gradient(ellipse 55% 38% at 92% 0%, rgba(234,88,12,0.12), transparent 52%), linear-gradient(180deg,#fffdf9 0%, var(--bg) 48%, #ffedd5 100%)",
  },
  {
    id: "grad-forest-glass",
    name: "林间玻璃",
    kind: "gradient",
    preview: "radial-gradient(ellipse at 20% 0%, rgba(22,163,74,0.22), transparent 50%), linear-gradient(180deg,#f0fdf4,#dcfce7)",
    layers: "radial-gradient(ellipse 70% 45% at 15% -8%, rgba(22,163,74,0.12), transparent 55%), linear-gradient(180deg,#ffffff 0%, var(--bg) 50%, #dcfce7 100%)",
  },
  {
    id: "grad-steel-horizon",
    name: "钢色地平",
    kind: "gradient",
    preview: "linear-gradient(180deg,#f1f5f9 0%,#94a3b8 45%,#334155 100%)",
    layers: "linear-gradient(180deg,rgba(255,255,255,0.85),rgba(241,245,249,0.5)), linear-gradient(180deg,#ffffff 0%, var(--bg) 40%, #cbd5e1 100%)",
  },
  {
    id: "grad-twin-beam",
    name: "双束光柱",
    kind: "gradient",
    preview: "radial-gradient(ellipse at 0% 0%, rgba(14,165,233,0.35), transparent 40%), radial-gradient(ellipse at 100% 0%, rgba(6,182,212,0.3), transparent 40%), #f8fafc",
    layers: "radial-gradient(ellipse 55% 40% at 0% -5%, rgba(14,165,233,0.16), transparent 50%), radial-gradient(ellipse 55% 40% at 100% -5%, rgba(6,182,212,0.14), transparent 50%), linear-gradient(180deg,#ffffff 0%, var(--bg) 55%, #f1f5f9 100%)",
  },
  {
    id: "grad-obsidian",
    name: "黑曜镜面",
    kind: "gradient",
    preview: "radial-gradient(ellipse at 50% 0%, rgba(51,65,85,0.5), transparent 50%), linear-gradient(180deg,#0f172a,#020617)",
    layers: "radial-gradient(ellipse 70% 45% at 50% -10%, rgba(148,163,184,0.12), transparent 55%), linear-gradient(180deg,#1e293b 0%, var(--bg) 50%, #020617 100%)",
  },
  {
    id: "grad-porcelain",
    name: "瓷白细纹",
    kind: "pattern",
    preview: "radial-gradient(rgba(15,23,42,0.06) 0.8px, transparent 1px) 0 0/14px 14px, #fafafa",
    layers: "radial-gradient(rgba(15,23,42,0.05) 0.8px, transparent 1px) 0 0/16px 16px, linear-gradient(180deg,#ffffff 0%, var(--bg) 60%, #f4f4f5 100%)",
  },
  {
    id: "grad-blueprint",
    name: "蓝图网格",
    kind: "pattern",
    preview: "linear-gradient(90deg,rgba(37,99,235,0.12) 1px,transparent 1px),linear-gradient(rgba(37,99,235,0.12) 1px,transparent 1px),#eff6ff",
    layers: "linear-gradient(180deg,rgba(255,255,255,0.75),rgba(239,246,255,0.9)),linear-gradient(90deg,rgba(37,99,235,0.06) 1px,transparent 1px) 0 0/24px 24px,linear-gradient(rgba(37,99,235,0.06) 1px,transparent 1px) 0 0/24px 24px,linear-gradient(180deg,#ffffff 0%,var(--bg) 100%)",
  },
  {
    id: "grad-sunset-glass",
    name: "暮色玻璃",
    kind: "gradient",
    preview: "radial-gradient(ellipse at 80% 0%, rgba(251,146,60,0.3), transparent 45%), radial-gradient(ellipse at 10% 100%, rgba(14,165,233,0.2), transparent 45%), #fff7ed",
    layers: "radial-gradient(ellipse 55% 38% at 88% 0%, rgba(251,146,60,0.14), transparent 52%), radial-gradient(ellipse 50% 35% at 8% 100%, rgba(14,165,233,0.1), transparent 50%), linear-gradient(180deg,#fffdf9 0%, var(--bg) 50%, #ffedd5 100%)",
  },
  {
    id: "grad-alpine",
    name: "高山清冽",
    kind: "gradient",
    preview: "radial-gradient(ellipse at 40% 0%, rgba(125,211,252,0.4), transparent 50%), linear-gradient(180deg,#f0f9ff,#e0f2fe)",
    layers: "radial-gradient(ellipse 75% 48% at 40% -10%, rgba(56,189,248,0.16), transparent 55%), linear-gradient(180deg,#ffffff 0%, var(--bg) 50%, #e0f2fe 100%)",
  },
  {
    id: "grad-carbon",
    name: "碳纤维纹",
    kind: "pattern",
    preview: "repeating-linear-gradient(45deg, #1e293b, #1e293b 2px, #0f172a 2px, #0f172a 6px)",
    layers: "linear-gradient(180deg,rgba(15,23,42,0.55),rgba(2,6,23,0.75)), repeating-linear-gradient(45deg,rgba(51,65,85,0.35),rgba(51,65,85,0.35) 2px,transparent 2px,transparent 8px), linear-gradient(180deg,#1e293b 0%, var(--bg) 100%)",
  },
  {
    id: "photo-biz-glass-office",
    name: "\u73bb\u7483\u529e\u516c\u5eca",
    kind: "photo",
    preview: 'url("/covers/biz-glass-office.jpg") center/cover',
    layers: photoLayers("/covers/biz-glass-office.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-desk-plant",
    name: "\u7eff\u690d\u5de5\u4f4d",
    kind: "photo",
    preview: 'url("/covers/biz-desk-plant.jpg") center/cover',
    layers: photoLayers("/covers/biz-desk-plant.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-laptop-hands",
    name: "\u952e\u5165\u4e13\u6ce8",
    kind: "photo",
    preview: 'url("/covers/biz-laptop-hands.jpg") center/cover',
    layers: photoLayers("/covers/biz-laptop-hands.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-team-table",
    name: "\u957f\u684c\u534f\u4f5c",
    kind: "photo",
    preview: 'url("/covers/biz-team-table.jpg") center/cover',
    layers: photoLayers("/covers/biz-team-table.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-team-smile",
    name: "\u56e2\u961f\u5408\u5f71",
    kind: "photo",
    preview: 'url("/covers/biz-team-smile.jpg") center/cover',
    layers: photoLayers("/covers/biz-team-smile.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-boardroom",
    name: "\u8463\u4e8b\u4f1a\u8bae\u5ba4",
    kind: "photo",
    preview: 'url("/covers/biz-boardroom.jpg") center/cover',
    layers: photoLayers("/covers/biz-boardroom.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-handshake",
    name: "\u5546\u52a1\u63e1\u624b",
    kind: "photo",
    preview: 'url("/covers/biz-handshake.jpg") center/cover',
    layers: photoLayers("/covers/biz-handshake.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-startup",
    name: "\u521b\u4e1a\u51b2\u523a",
    kind: "photo",
    preview: 'url("/covers/biz-startup.jpg") center/cover',
    layers: photoLayers("/covers/biz-startup.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-macbook",
    name: "\u6781\u7b80\u7b14\u7535",
    kind: "photo",
    preview: 'url("/covers/biz-macbook.jpg") center/cover',
    layers: photoLayers("/covers/biz-macbook.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-present",
    name: "\u5546\u52a1\u6f14\u8bb2",
    kind: "photo",
    preview: 'url("/covers/biz-present.jpg") center/cover',
    layers: photoLayers("/covers/biz-present.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-pro-portrait",
    name: "\u804c\u573a\u8096\u50cf",
    kind: "photo",
    preview: 'url("/covers/biz-pro-portrait.jpg") center/cover',
    layers: photoLayers("/covers/biz-pro-portrait.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-engineer",
    name: "\u5de5\u7a0b\u73b0\u573a",
    kind: "photo",
    preview: 'url("/covers/biz-engineer.jpg") center/cover',
    layers: photoLayers("/covers/biz-engineer.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-cowork-bright",
    name: "\u660e\u4eae\u8054\u5408\u529e\u516c",
    kind: "photo",
    preview: 'url("/covers/biz-cowork-bright.jpg") center/cover',
    layers: photoLayers("/covers/biz-cowork-bright.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-sofa-talk",
    name: "\u6c99\u53d1\u4f1a\u8c08",
    kind: "photo",
    preview: 'url("/covers/biz-sofa-talk.jpg") center/cover',
    layers: photoLayers("/covers/biz-sofa-talk.jpg", PHOTO_VEIL_WARM),
  },
  {
    id: "photo-biz-skyline-day",
    name: "\u65e5\u95f4\u5929\u9645\u7ebf",
    kind: "photo",
    preview: 'url("/covers/biz-skyline-day.jpg") center/cover',
    layers: photoLayers("/covers/biz-skyline-day.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-city-aerial",
    name: "\u90fd\u5e02\u822a\u62cd",
    kind: "photo",
    preview: 'url("/covers/biz-city-aerial.jpg") center/cover',
    layers: photoLayers("/covers/biz-city-aerial.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-glass-tower",
    name: "\u73bb\u7483\u5854\u697c",
    kind: "photo",
    preview: 'url("/covers/biz-glass-tower.jpg") center/cover',
    layers: photoLayers("/covers/biz-glass-tower.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-street",
    name: "\u73b0\u4ee3\u8857\u533a",
    kind: "photo",
    preview: 'url("/covers/biz-street.jpg") center/cover',
    layers: photoLayers("/covers/biz-street.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-neon-alley",
    name: "\u9713\u8679\u5df7\u9053",
    kind: "photo",
    preview: 'url("/covers/biz-neon-alley.jpg") center/cover',
    layers: photoLayers("/covers/biz-neon-alley.jpg", PHOTO_VEIL_CYBER),
  },
  {
    id: "photo-biz-charts",
    name: "\u56fe\u8868\u6848\u5934",
    kind: "photo",
    preview: 'url("/covers/biz-charts.jpg") center/cover',
    layers: photoLayers("/covers/biz-charts.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-dashboard",
    name: "\u6570\u636e\u4eea\u8868\u76d8",
    kind: "photo",
    preview: 'url("/covers/biz-dashboard.jpg") center/cover',
    layers: photoLayers("/covers/biz-dashboard.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-code-dark",
    name: "\u6697\u8272\u4ee3\u7801",
    kind: "photo",
    preview: 'url("/covers/biz-code-dark.jpg") center/cover',
    layers: photoLayers("/covers/biz-code-dark.jpg", PHOTO_VEIL_CYBER),
  },
  {
    id: "photo-biz-circuit",
    name: "\u7535\u8def\u7eb9\u7406",
    kind: "photo",
    preview: 'url("/covers/biz-circuit.jpg") center/cover',
    layers: photoLayers("/covers/biz-circuit.jpg", PHOTO_VEIL_CYBER),
  },
  {
    id: "photo-biz-matrix",
    name: "\u77e9\u9635\u4ee3\u7801",
    kind: "photo",
    preview: 'url("/covers/biz-matrix.jpg") center/cover',
    layers: photoLayers("/covers/biz-matrix.jpg", PHOTO_VEIL_CYBER),
  },
  {
    id: "photo-biz-laptop-dark",
    name: "\u6697\u8c03\u7b14\u7535",
    kind: "photo",
    preview: 'url("/covers/biz-laptop-dark.jpg") center/cover',
    layers: photoLayers("/covers/biz-laptop-dark.jpg", PHOTO_VEIL_CYBER),
  },
  {
    id: "photo-biz-gadgets",
    name: "\u79d1\u6280\u88c5\u7f6e",
    kind: "photo",
    preview: 'url("/covers/biz-gadgets.jpg") center/cover',
    layers: photoLayers("/covers/biz-gadgets.jpg", PHOTO_VEIL_CYBER),
  },
  {
    id: "photo-biz-servers",
    name: "\u673a\u67dc\u9635\u5217",
    kind: "photo",
    preview: 'url("/covers/biz-servers.jpg") center/cover',
    layers: photoLayers("/covers/biz-servers.jpg", PHOTO_VEIL_CYBER),
  },
  {
    id: "photo-biz-standup",
    name: "\u7ad9\u4f1a\u8ba8\u8bba",
    kind: "photo",
    preview: 'url("/covers/biz-standup.jpg") center/cover',
    layers: photoLayers("/covers/biz-standup.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-conference",
    name: "\u5927\u578b\u4f1a\u573a",
    kind: "photo",
    preview: 'url("/covers/biz-conference.jpg") center/cover',
    layers: photoLayers("/covers/biz-conference.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-pair",
    name: "\u7ed3\u5bf9\u5de5\u4f5c",
    kind: "photo",
    preview: 'url("/covers/biz-pair.jpg") center/cover',
    layers: photoLayers("/covers/biz-pair.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-sticky",
    name: "\u4fbf\u7b7e\u5de5\u574a",
    kind: "photo",
    preview: 'url("/covers/biz-sticky.jpg") center/cover',
    layers: photoLayers("/covers/biz-sticky.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-keynote",
    name: "\u9886\u8896\u6f14\u8bb2",
    kind: "photo",
    preview: 'url("/covers/biz-keynote.jpg") center/cover',
    layers: photoLayers("/covers/biz-keynote.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-client",
    name: "\u5ba2\u6237\u4f1a\u9762",
    kind: "photo",
    preview: 'url("/covers/biz-client.jpg") center/cover',
    layers: photoLayers("/covers/biz-client.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-keyboard",
    name: "\u952e\u76d8\u7279\u5199",
    kind: "photo",
    preview: 'url("/covers/biz-keyboard.jpg") center/cover',
    layers: photoLayers("/covers/biz-keyboard.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-students",
    name: "\u9752\u5e74\u6210\u957f",
    kind: "photo",
    preview: 'url("/covers/biz-students.jpg") center/cover',
    layers: photoLayers("/covers/biz-students.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-collab",
    name: "\u534f\u4f5c\u7814\u8ba8",
    kind: "photo",
    preview: 'url("/covers/biz-collab.jpg") center/cover',
    layers: photoLayers("/covers/biz-collab.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-training",
    name: "\u57f9\u8bad\u6559\u5ba4",
    kind: "photo",
    preview: 'url("/covers/biz-training.jpg") center/cover',
    layers: photoLayers("/covers/biz-training.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-books",
    name: "\u4e66\u67b6\u5149\u5f71",
    kind: "photo",
    preview: 'url("/covers/biz-books.jpg") center/cover',
    layers: photoLayers("/covers/biz-books.jpg", PHOTO_VEIL_WARM),
  },
  {
    id: "photo-biz-online-learn",
    name: "\u5728\u7ebf\u5b66\u4e60",
    kind: "photo",
    preview: 'url("/covers/biz-online-learn.jpg") center/cover',
    layers: photoLayers("/covers/biz-online-learn.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-lecture",
    name: "\u9636\u68af\u8bb2\u5802",
    kind: "photo",
    preview: 'url("/covers/biz-lecture.jpg") center/cover',
    layers: photoLayers("/covers/biz-lecture.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-learner",
    name: "\u5b66\u5458\u7b14\u7535",
    kind: "photo",
    preview: 'url("/covers/biz-learner.jpg") center/cover',
    layers: photoLayers("/covers/biz-learner.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-classroom",
    name: "\u73b0\u4ee3\u6559\u5ba4",
    kind: "photo",
    preview: 'url("/covers/biz-classroom.jpg") center/cover',
    layers: photoLayers("/covers/biz-classroom.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-ai-glow",
    name: "AI \u5149\u611f",
    kind: "photo",
    preview: 'url("/covers/biz-ai-glow.jpg") center/cover',
    layers: photoLayers("/covers/biz-ai-glow.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-abstract-3d",
    name: "\u7acb\u4f53\u62bd\u8c61",
    kind: "photo",
    preview: 'url("/covers/biz-abstract-3d.jpg") center/cover',
    layers: photoLayers("/covers/biz-abstract-3d.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-ui-code",
    name: "\u754c\u9762\u4ee3\u7801",
    kind: "photo",
    preview: 'url("/covers/biz-ui-code.jpg") center/cover',
    layers: photoLayers("/covers/biz-ui-code.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-present-slide",
    name: "\u6295\u5f71\u6c47\u62a5",
    kind: "photo",
    preview: 'url("/covers/biz-present-slide.jpg") center/cover',
    layers: photoLayers("/covers/biz-present-slide.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-hotel-lobby",
    name: "\u5546\u52a1\u5927\u5802",
    kind: "photo",
    preview: 'url("/covers/biz-hotel-lobby.jpg") center/cover',
    layers: photoLayers("/covers/biz-hotel-lobby.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-skyline-dusk",
    name: "\u9ec4\u660f\u5929\u9645",
    kind: "photo",
    preview: 'url("/covers/biz-skyline-dusk.jpg") center/cover',
    layers: photoLayers("/covers/biz-skyline-dusk.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-handshake-desk",
    name: "\u684c\u524d\u63e1\u624b",
    kind: "photo",
    preview: 'url("/covers/biz-handshake-desk.jpg") center/cover',
    layers: photoLayers("/covers/biz-handshake-desk.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-lab-auto",
    name: "\u667a\u80fd\u4ea7\u7ebf",
    kind: "photo",
    preview: 'url("/covers/biz-lab-auto.jpg") center/cover',
    layers: photoLayers("/covers/biz-lab-auto.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-kanban",
    name: "\u770b\u677f\u89c4\u5212",
    kind: "photo",
    preview: 'url("/covers/biz-kanban.jpg") center/cover',
    layers: photoLayers("/covers/biz-kanban.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-robot",
    name: "\u673a\u5668\u4eba\u81c2",
    kind: "photo",
    preview: 'url("/covers/biz-robot.jpg") center/cover',
    layers: photoLayers("/covers/biz-robot.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-vr",
    name: "\u6c89\u6d78\u4f53\u9a8c",
    kind: "photo",
    preview: 'url("/covers/biz-vr.jpg") center/cover',
    layers: photoLayers("/covers/biz-vr.jpg", PHOTO_VEIL_CYBER),
  },
  {
    id: "photo-biz-fintech",
    name: "\u91d1\u878d\u79d1\u6280",
    kind: "photo",
    preview: 'url("/covers/biz-fintech.jpg") center/cover',
    layers: photoLayers("/covers/biz-fintech.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-cafe-work",
    name: "\u5496\u5561\u9986\u529e\u516c",
    kind: "photo",
    preview: 'url("/covers/biz-cafe-work.jpg") center/cover',
    layers: photoLayers("/covers/biz-cafe-work.jpg", PHOTO_VEIL_WARM),
  },
  {
    id: "photo-biz-loft",
    name: "\u5de5\u4e1a\u98ce\u529e\u516c",
    kind: "photo",
    preview: 'url("/covers/biz-loft.jpg") center/cover',
    layers: photoLayers("/covers/biz-loft.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-dev-team",
    name: "\u7814\u53d1\u56e2\u961f",
    kind: "photo",
    preview: 'url("/covers/biz-dev-team.jpg") center/cover',
    layers: photoLayers("/covers/biz-dev-team.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-mobile",
    name: "\u79fb\u52a8\u529e\u516c",
    kind: "photo",
    preview: 'url("/covers/biz-mobile.jpg") center/cover',
    layers: photoLayers("/covers/biz-mobile.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-exec",
    name: "\u9ad8\u7ba1\u8096\u50cf",
    kind: "photo",
    preview: 'url("/covers/biz-exec.jpg") center/cover',
    layers: photoLayers("/covers/biz-exec.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-sky-blue",
    name: "\u78a7\u7a7a\u90fd\u4f1a",
    kind: "photo",
    preview: 'url("/covers/biz-sky-blue.jpg") center/cover',
    layers: photoLayers("/covers/biz-sky-blue.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-code2",
    name: "\u7ec8\u7aef\u6d41\u5149",
    kind: "photo",
    preview: 'url("/covers/biz-code2.jpg") center/cover',
    layers: photoLayers("/covers/biz-code2.jpg", PHOTO_VEIL_CYBER),
  },
  {
    id: "photo-biz-elearn",
    name: "\u4e91\u7aef\u8bfe\u5802",
    kind: "photo",
    preview: 'url("/covers/biz-elearn.jpg") center/cover',
    layers: photoLayers("/covers/biz-elearn.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-hall-seat",
    name: "\u4f1a\u5802\u5ea7\u5e2d",
    kind: "photo",
    preview: 'url("/covers/biz-hall-seat.jpg") center/cover',
    layers: photoLayers("/covers/biz-hall-seat.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-slide2",
    name: "\u7b80\u62a5\u73b0\u573a",
    kind: "photo",
    preview: 'url("/covers/biz-slide2.jpg") center/cover',
    layers: photoLayers("/covers/biz-slide2.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-design-desk",
    name: "\u8bbe\u8ba1\u684c\u9762",
    kind: "photo",
    preview: 'url("/covers/biz-design-desk.jpg") center/cover',
    layers: photoLayers("/covers/biz-design-desk.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-coin-tech",
    name: "\u6570\u5b57\u91d1\u878d",
    kind: "photo",
    preview: 'url("/covers/biz-coin-tech.jpg") center/cover',
    layers: photoLayers("/covers/biz-coin-tech.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-cafe2",
    name: "\u8857\u89d2\u529e\u516c",
    kind: "photo",
    preview: 'url("/covers/biz-cafe2.jpg") center/cover',
    layers: photoLayers("/covers/biz-cafe2.jpg", PHOTO_VEIL_WARM),
  },
  {
    id: "photo-biz-grow",
    name: "\u6210\u957f\u5b66\u4e60",
    kind: "photo",
    preview: 'url("/covers/biz-grow.jpg") center/cover',
    layers: photoLayers("/covers/biz-grow.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-travel",
    name: "\u5546\u65c5\u5ba2\u5385",
    kind: "photo",
    preview: 'url("/covers/biz-travel.jpg") center/cover',
    layers: photoLayers("/covers/biz-travel.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-crowd-conf",
    name: "\u5cf0\u4f1a\u73b0\u573a",
    kind: "photo",
    preview: 'url("/covers/biz-crowd-conf.jpg") center/cover',
    layers: photoLayers("/covers/biz-crowd-conf.jpg", PHOTO_VEIL_COOL),
  },
  {
    id: "photo-biz-women-tech",
    name: "\u79d1\u6280\u5973\u6027",
    kind: "photo",
    preview: 'url("/covers/biz-women-tech.jpg") center/cover',
    layers: photoLayers("/covers/biz-women-tech.jpg", PHOTO_VEIL_LIGHT),
  },
  {
    id: "photo-biz-lounge2",
    name: "\u4f11\u95f2\u6d3d\u8c08",
    kind: "photo",
    preview: 'url("/covers/biz-lounge2.jpg") center/cover',
    layers: photoLayers("/covers/biz-lounge2.jpg", PHOTO_VEIL_WARM),
  },
];

/** 部分新照片配一键主题包，便于站长快速选用 */
export const EXTRA_THEME_PACKS: ThemePack[] = [
  {
    id: "pack-glass-office",
    name: "玻璃办公",
    tagline: "通透现代机构风",
    paletteId: "sky-fresh",
    backgroundId: "photo-biz-glass-office",
    cover: "url(\"/covers/biz-glass-office.jpg\") center/cover",
  },
  {
    id: "pack-skyline",
    name: "都会天际",
    tagline: "都市航拍 + 冷灰",
    paletteId: "cool-slate",
    backgroundId: "photo-biz-city-aerial",
    cover: "url(\"/covers/biz-city-aerial.jpg\") center/cover",
  },
  {
    id: "pack-neon-alley",
    name: "霓虹巷道",
    tagline: "夜景科技感",
    paletteId: "cyber-neon",
    backgroundId: "photo-biz-neon-alley",
    cover: "url(\"/covers/biz-neon-alley.jpg\") center/cover",
  },
  {
    id: "pack-boardroom",
    name: "董事会议",
    tagline: "正式商务现场",
    paletteId: "cool-slate",
    backgroundId: "photo-biz-boardroom",
    cover: "url(\"/covers/biz-boardroom.jpg\") center/cover",
  },
  {
    id: "pack-ai-glow",
    name: "智能光感",
    tagline: "AI 意象 + 天蓝",
    paletteId: "sky-fresh",
    backgroundId: "photo-biz-ai-glow",
    cover: "url(\"/covers/biz-ai-glow.jpg\") center/cover",
  },
  {
    id: "pack-library",
    name: "书廊暖光",
    tagline: "阅读学习氛围",
    paletteId: "warm-ink",
    backgroundId: "photo-biz-books",
    cover: "url(\"/covers/biz-books.jpg\") center/cover",
  },
  {
    id: "pack-servers",
    name: "数据机柜",
    tagline: "基础设施科技",
    paletteId: "cool-slate",
    backgroundId: "photo-biz-servers",
    cover: "url(\"/covers/biz-servers.jpg\") center/cover",
  },
  {
    id: "pack-collab",
    name: "协作研讨",
    tagline: "团队共创现场",
    paletteId: "sky-fresh",
    backgroundId: "photo-biz-collab",
    cover: "url(\"/covers/biz-collab.jpg\") center/cover",
  },
  {
    id: "pack-blueprint",
    name: "蓝图网格",
    tagline: "规划感纹理底",
    paletteId: "sky-fresh",
    backgroundId: "grad-blueprint",
    cover: "linear-gradient(90deg,rgba(37,99,235,0.12) 1px,transparent 1px),linear-gradient(rgba(37,99,235,0.12) 1px,transparent 1px),#eff6ff",
  },
  {
    id: "pack-executive",
    name: "高管墨蓝",
    tagline: "深色商务站风",
    paletteId: "cool-slate",
    backgroundId: "grad-executive-ink",
    cover: "linear-gradient(160deg,#1e3a5f,#0c1929 60%,#082f49)",
  },
  {
    id: "pack-pearl",
    name: "珍珠白空",
    tagline: "极简明亮门户",
    paletteId: "sky-fresh",
    backgroundId: "grad-pearl-sky",
    cover: "radial-gradient(ellipse 80% 50% at 12% -8%, rgba(56,189,248,0.28), transparent 55%), linear-gradient(180deg,#ffffff,#eef6ff 55%,#e8f0f8)",
  },
  {
    id: "pack-loft",
    name: "工业办公",
    tagline: "Loft 现代感",
    paletteId: "cool-slate",
    backgroundId: "photo-biz-loft",
    cover: "url(\"/covers/biz-loft.jpg\") center/cover",
  },
];
